### ISSUE TITLE
Font family and CSS grid layout for the projects section

### ISSUE THREAD

**Issue by jfoyarzo** [MahdiAghaali/My-Portfolio#9]
Your code is looking great! Just a few suggestions to follow the figma design: 
- You can use [google fonts](https://fonts.google.com/knowledge/using_type/using_web_fonts) to display the correct font family (Poppins and Playfair display)
- For the projects section you can use the CSS [grid layout](https://css-tricks.com/snippets/css/complete-guide-grid/) to arrange the projects, using a grid of 12x12 could help you display them similar to the figma template

Great work! 👍

**Comment by Alhajideen** [comment]
You did an amazing work, I like how you used grid and flexbox for your layouts and the amazing animations on your images.
Just one suggestion i think will make your code more beautiful and give a better ux;
 - I think you should make the two columns in your first section after the navigation bar (where you introduced yourself) to have an equal width of 50% each so that they wont overlap on smaller screens.
 
Happy coding 👍
